import {
  Folder,
  Terminal,
  Activity,
  Radar,
  User,
  Trophy,
  Network,
  Sparkles,
  Award,
  Mail,
  FileText,
  Code,
  Flame,
  Github,
  Linkedin,
  Twitter,
  Globe,
  Medal,
  Zap,
  Flag,
  Database,
  Bot,
  Scan,
  Search,
  Sun,
  Moon,
  Menu,
  Download,
  ExternalLink,
  CircleDot,
  Cpu,
  Layers,
  Workflow,
  ChevronRight,
  GitBranch,
} from "lucide-react";

const Icon = {
  folder: Folder,
  terminal: Terminal,
  activity: Activity,
  radar: Radar,
  user: User,
  trophy: Trophy,
  network: Network,
  sparkles: Sparkles,
  award: Award,
  mail: Mail,
  "file-text": FileText,
  code: Code,
  flame: Flame,
  github: Github,
  linkedin: Linkedin,
  twitter: Twitter,
  codeforces: Code,
  codechef: Trophy,
  chef: Trophy,
  leetcode: Code,
  globe: Globe,
  medal: Medal,
  zap: Zap,
  flag: Flag,
  database: Database,
  bot: Bot,
  scan: Scan,
  search: Search,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  download: Download,
  external: ExternalLink,
  circle: CircleDot,
  cpu: Cpu,
  layers: Layers,
  workflow: Workflow,
  chevron: ChevronRight,
  branch: GitBranch,
};

const Lucide = ({ name, size = 16, ...props }) => {
  const C = Icon[name] ?? Code;
  return <C size={size} strokeWidth={1.8} {...props} />;
};

export default Lucide;
